Add: Automatic Configuration of Client Instances
alauda/go-redis-client pull request #4
Opened 2019-05-15 08:55 UTC by aiyijing

### util/util/go
- Get params from env 
- Get params from voluem
### config.go
- merge params from env and volume
- create option by viper
### client.go
- add func MgetByPipeline
### interface.go
### more and unimportance
...

2019-05-15 11:06 UTC, hangyan requested changes
文件命名格式也不对。
应该是  auto_config_redisclient.go类似的

2019-05-15 11:06 UTC, hangyan commented on AutoConfigRedisClient.go
> +//  Create Client:Combining configuration file parameters and environment variable parameters,
注释的格式不对。你看下官方的或者社区的例子是什么样的

2019-05-20 03:27 UTC, hangyan commented on auto_config_redisclient.go
> +	opts,err := CustomizedOptionsInEnv(rwType)
In -> From

2019-05-20 03:31 UTC, hangyan requested changes

2019-05-20 03:31 UTC, hangyan commented on auto_config_redisclient.go
> +func AutoConfigRedisClientInVolume(rwType RWType)(* Client,error){
In -> From

2019-05-20 06:01 UTC, aiyijing commented on auto_config_redisclient.go
> +func AutoConfigRedisClientInVolume(rwType RWType)(* Client,error){
命名格式已经refactor

2019-05-20 06:14 UTC, hangyan requested changes

2019-05-20 06:14 UTC, hangyan commented on util/util.go
> +func GetEnvVariable(key string) string{
这个封装没有任何意义

2019-05-24 07:35 UTC, hangyan commented
dup of #5

2019-05-24 07:35 UTC, closed without merging