Add: Automatic Configuration of Client Instances
alauda/go-redis-client pull request #5
Opened 2019-05-20 08:27 UTC by aiyijing

2019-05-20 09:18 UTC, hangyan requested changes

2019-05-20 09:18 UTC, hangyan commented on client.go
> +// isCluster
这些注释都没写

2019-05-20 09:19 UTC, hangyan requested changes

2019-05-20 09:19 UTC, hangyan commented on util/util.go
> +//LoadParamsFromVolume
要写清楚这个函数具体干啥的，不能光写个名字

2019-05-21 02:00 UTC, hangyan commented on config.go
> +var ConfigKey=[]string{
ConfigKeys

2019-05-21 02:00 UTC, hangyan commented on config.go
> +//addrStructure will create ADDR,For example string: "host:port"
非export的函数可以不写注释

2019-05-21 02:00 UTC, hangyan requested changes

2019-05-21 02:00 UTC, hangyan commented on config.go
> +func CustomizedOption(viper* viper.Viper,rwType RWType) *Options{
这个函数要暴露吗？

2019-05-21 02:01 UTC, hangyan commented on util/util.go
> +	"github.com/Sirupsen/logrus"
你看下这个库的文档，好像现在使用小写的名字来import了

2019-05-21 02:02 UTC, hangyan requested changes

2019-05-21 02:02 UTC, hangyan commented on util/util.go
> +	DefaultDir      = "/etc/pass/"
这些也要加注释的。 pass啥意思？

2019-05-22 08:31 UTC, hangyan commented on client.go
> +// isCluster determine whether client is a cluster model
isCluster -> IsCluster

2019-05-22 08:32 UTC, hangyan commented on util/util.go
> +	DefaultDir      = "/etc/paas/"	// default config file search dir
这个注释不是写在后面，是跟函数一样的格式

2019-05-22 08:35 UTC, hangyan commented on client.go
> +func (r *Client) MGetByPipeline(keys ...string) ([]string, error) {
这个函数因为是自己实现的，最好加个单元测试，参考krobelus的

2019-05-24 07:31 UTC, hangyan commented on util/util.go
> +	// default config file search dir
格式还是不对。跟函数一样，要以 具体的名字开头。比如  DefaultDir is default config file serach dir

2019-05-24 07:33 UTC, hangyan commented
另，以后的PR不要以自己的名字之类的命名，以实际的feature/bug的名字命名

2019-05-24 07:36 UTC, hangyan commented on README.en.md
> +# alauda/go-redis-client
这两个readme文档需要在README.md中加个链接引用上。

2019-05-24 07:37 UTC, hangyan commented on options.go
> +	OnlyWrite    RWType ="WRITER"
这也要加注释，而且OnlyWrite没有用上？

2019-05-24 07:40 UTC, hangyan commented on util/util.go
> +		logrus.Warnf("ConfigDirKey Not exsit in env Use default dir %s", DefaultDir)
exsit -> exist

2019-05-24 07:40 UTC, hangyan commented on util/util.go
> +		logrus.Warnf("ConfigNameKey not exsit in env Use default name %s", DefaultFileName)
exsit -> exist

2019-05-24 07:43 UTC, hangyan commented
代码需要用 gofmt 排版下，对齐很奇怪

2019-05-24 07:45 UTC, hangyan commented on config.go
> +// customizedOptionsFromFullVariable Customized Options by  Voluem and Env
typo Voluem -> Volume

2019-05-24 07:48 UTC, hangyan commented
`/etc/paas/` 为什么 configdir默认是这个？

2019-05-24 07:49 UTC, hangyan commented
`ENV_PREFIX` 是否可以为空？为空的是不是空字符串是默认值？最好是有一个默认值。

2019-05-24 09:31 UTC, aiyijing commented on options.go
> +	OnlyWrite    RWType ="WRITER"
加上注释了，用户在使用的时候需要自己引用

2019-05-27 02:49 UTC, merged